### PR TITLE
fix: initialization SSL Context

### LINKED ISSUE #55: Cannot use TLS connection with PutInfluxDatabase_2
I cannot get the connection to an InfluxDB2 server (via Apache Reverse Proxy with TLS and Client-Auth) to work.

I always get this error, when PutInfluxDatabase_2/StandardInfluxDatabaseService_2 tries to establish a connection:
```
2021-05-11 07:51:48,338 ERROR [Timer-Driven Process Thread-2] o.i.nifi.processors.PutInfluxDatabase_2 PutInfluxDatabase_2[id=fe4d3e03-0177-1000-218e-e4211ca049d3] Failed to insert into influxDB due to PK
IX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target: com.influxdb.exceptions.InfluxException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
com.influxdb.exceptions.InfluxException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at com.influxdb.internal.AbstractRestClient.execute(AbstractRestClient.java:84)
        at com.influxdb.client.internal.WriteApiBlockingImpl.write(WriteApiBlockingImpl.java:229)
...
```

However, the **same** StandardRestrictedSSLContextService with the same target URL does work, when used in a GetHTTP processor.

So I'm quite certain that the TLS configuration is correct.

Are there any known issues with the https client used by StandardInfluxDatabaseService_2 regarding TLS client authentication, multi level CA hierarchies etc.?

### PR DESCRIPTION
**Pull request by bednar**
Closes #55

Simplify how to initialize SSL context - corresponding to changes in: https://github.com/apache/nifi/commit/441781cec50f77d9f1e65093f55bbd614b8c5ec6#diff-454d4c0f48c7f7b7c3d3fa5eeb53ce2af7ff032921a5fdfde7012a044525b9d6

- [x] CHANGELOG.md updated
- [x] Rebased/mergeable
- [x] Tests pass
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by bednar** [comment]
Snapshot bundle: [nifi-influx-database-nar-1.11.0-SNAPSHOT.nar.zip](https://github.com/influxdata/nifi-influxdb-bundle/files/6570280/nifi-influx-database-nar-1.11.0-SNAPSHOT.nar.zip)

File: nifi-influx-database-services/src/test/java/org/influxdata/nifi/services/AbstractTestStandardInfluxDatabaseService_2.java [hunk 1]
```diff
@@ -57,7 +56,7 @@ protected void setUp(@NonNull final Supplier<Answer> answerConnect) throws Excep
                 .connect(Mockito.anyString(),
                         Mockito.any(),
                         Mockito.any(),
-                        Mockito.any(),
+						Mockito.any(),
```
Comment (rhajek) [inline nifi-influx-database-services/src/test/java/org/influxdata/nifi/services/AbstractTestStandardInfluxDatabaseService_2.java:59]: bad indentation

File: nifi-influx-database-services/src/test/java/org/influxdata/nifi/services/AbstractTestStandardInfluxDatabaseService.java [hunk 2]
```diff
@@ -58,7 +58,7 @@ protected void setUp(@NonNull final Supplier<Answer> answerConnect) throws Excep
                         Mockito.any(),
                         Mockito.any(),
                         Mockito.any(),
-                        Mockito.any(),
+						Mockito.any(),
```
Comment (rhajek) [inline nifi-influx-database-services/src/test/java/org/influxdata/nifi/services/AbstractTestStandardInfluxDatabaseService.java:61]: bad indentation

**Review by rhajek — APPROVED** [review]
